### ISSUE TITLE
Dev UX improvement proposals

### ISSUE THREAD

**Issue by mradkov** [hackbg/fadroma#193]
When you run `pnpm test:devnet` in a project initially a docker container is started with a local network where tests are to be ran.
After the command exits the container is still running. This is a problem on a second invocation of this command as then the result is an error saying a container is already running:

![image](https://github.com/hackbg/fadroma/assets/13139371/bc8d3636-8142-4f1d-8b03-aa3fe1d7610a)

Currently the workaround is to `docker ps` check the id of the container and `docker stop ...` it so this does not throw on the next `pnpm test:devnet` invocation.

In addition to what could be a bug somewhere, I see this as an opportunity to plug a small UX improvement here:
- (optionally) Add a flag `--fresh` (could be better worded) which stop/remove the current container and start a fresh `devnet` which the user command will be executed upon.

**Comment by egasimus** [comment]
The `304` issue has been fixed in 9234d64, please test to confirm that it works for you.

That aside, I agree that devnet management can be improved.

>(optionally) Add a flag --fresh (could be better worded) which stop/remove the current container and start a fresh devnet which the user command will be executed upon.

There is already the `reset` command, e.g. `pnpm devnet reset`, which nukes the current devnet so that the next deploy/test command would start with a fresh container.
